# Generated by Django 6.0.3 on 2026-03-16 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RelacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(default=0)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('codigo_produto', models.CharField(blank=True, max_length=80)),
                ('ok', models.BooleanField(default=False)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('odf', models.CharField(blank=True, max_length=80)),
                ('data', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('relacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='producao.relacao')),
            ],
            options={
                'ordering': ['indice', 'id'],
            },
        ),
    ]
