# Generated by Django 6.0.3 on 2026-03-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_relacao_relacaoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('produtos', models.ManyToManyField(blank=True, related_name='categorias', to='producao.produto')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
