# Generated by Django 6.0.3 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producao", "0003_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="relacaoitem",
            name="parcial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]

